/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/

var findTheDifference = function(s, t) {
    let map = new Map();
    for(let char of s){
        if(!map.has(char)){
            map.set(char,1)
        }else{
            map.set(char,map.get(char)+1)
        }
    }
    for(let char of t){
        if(!map.has(char)) return char;
        else{
            map.set(char,map.get(char)-1)
            }
    }
    for(let entry of map.entries()){
        if(entry[1] !=0){
            return entry[0]
        }
    }
};
====================================================================================================================

var findTheDifference = function(s, t) {
    let res = 0;
    for(let char of t){
        res += char.charCodeAt(0);
    }
    for(let char of s){
        res -= char.charCodeAt(0)
    }
    return String.fromCharCode(res)  
};
